name = "StableFluids"
uuid = "e8a07b15-bd3f-4648-a12a-4ed35719f4f2"
authors = ["luinux"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-657024d3d0a0"

[targets]
test = ["Test"]
